// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn-yySTlKwoqSFG2z9hVFM9J_QW3TZjwc',
    appId: '1:582322152682:web:ab594ce9404b509ae62393',
    messagingSenderId: '582322152682',
    projectId: 'jobportal-5f2df',
    authDomain: 'jobportal-5f2df.firebaseapp.com',
    storageBucket: 'jobportal-5f2df.firebasestorage.app',
    measurementId: 'G-J0WB1Z9GS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9kS-RVZhTcTLLFTx9PKhrCpM3kpA5Fw0',
    appId: '1:582322152682:android:5b35625b24b56e34e62393',
    messagingSenderId: '582322152682',
    projectId: 'jobportal-5f2df',
    storageBucket: 'jobportal-5f2df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO9soCGATXwtuzg3Bxqf4fTBpgiltI0_w',
    appId: '1:582322152682:ios:b531eeca8045c1ece62393',
    messagingSenderId: '582322152682',
    projectId: 'jobportal-5f2df',
    storageBucket: 'jobportal-5f2df.firebasestorage.app',
    iosClientId: '582322152682-9sen3j4ru3fsf4j7nmtl8jaspuntoan1.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobportal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO9soCGATXwtuzg3Bxqf4fTBpgiltI0_w',
    appId: '1:582322152682:ios:b531eeca8045c1ece62393',
    messagingSenderId: '582322152682',
    projectId: 'jobportal-5f2df',
    storageBucket: 'jobportal-5f2df.firebasestorage.app',
    iosClientId: '582322152682-9sen3j4ru3fsf4j7nmtl8jaspuntoan1.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobportal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn-yySTlKwoqSFG2z9hVFM9J_QW3TZjwc',
    appId: '1:582322152682:web:ecd43bc28c637d50e62393',
    messagingSenderId: '582322152682',
    projectId: 'jobportal-5f2df',
    authDomain: 'jobportal-5f2df.firebaseapp.com',
    storageBucket: 'jobportal-5f2df.firebasestorage.app',
    measurementId: 'G-RVV0V961SR',
  );
}
